language: php

sudo: required

services:
  - docker

php:
  - 7.1

before_script:
  - cp app.travis.yml app.yml
  - composer self-update
  - composer install --no-interaction
  - docker-compose up

script:
  - vendor/bin/phpunit tests/